name: Bug Report
description: Report an issue.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        # Bug Report
  - type: checkboxes
    attributes:
      label: Are you up to date?
      description: Make sure you have the most recent version installed.
      options:
        - label: I've confirmed that I am completely up to date.
          required: true
  - type: checkboxes
    attributes:
      label: Does the problem exist in Dev?
      description: Verify that the issue does not occur on the Dev Branch otherwise it will be closed without further notice.
      options:
        - label: I've verified that the problem persists in the Dev Branch.
          required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      description: What browser were you using?
      placeholder: Google Chrome, Microsoft Edge, Firefox, Opera
    validations:
      required: true
  - type: input
    id: page-url
    attributes:
      label: Page URL
      placeholder: https://www.roblox.com/home
    validations:
      required: false
  - type: dropdown
    id: channel
    attributes:
      label: Channel
      description: What channel you were on when it occured?
      options:
        - Release
        - Beta
        - Dev
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - CSS
        - JavaScript
        - Both
    validations:
      required: true
  - type: textarea
    id: describe-issue
    attributes:
      label: Describe the Problem
      description: Describe or share a photo or video of the issue you're facing as well as the expected behavior, and any steps to reproduce it.
    validations:
      required: true